In [7]:
import pandas as pd

In [8]:
old_df = pd.read_excel('DAK Rocks Old.xlsx')
new_df = pd.read_excel('DAK Rocks UPDATED.xlsx')

In [9]:
merged_df = new_df.merge(old_df[['Claim Number', 'Include', 'Theme']], on='Claim Number', how='left')

In [10]:
merged_df = pd.merge(new_df, old_df[['Claim Number', 'Include', 'Theme']], on='Claim Number', how='left', suffixes=('', '_old'))

# Update the 'Include' and 'Theme' columns in the new dataframe based on the old dataframe
merged_df['Include'] = merged_df['Include_old'].combine_first(merged_df['Include'])
merged_df['Theme'] = merged_df['Theme_old'].combine_first(merged_df['Theme'])

# Drop the temporary columns
merged_df.drop(columns=['Include_old', 'Theme_old'], inplace=True)

In [11]:
merged_df

,Setid,Client ID-Claim,Date of Incident/Loss,Fiscal Year,Fiscal Month,Time of Incident/Loss,Incident to Claim Date,Occurrence Number,Claim Number,Age at Date of Incident,...,Litigation Desc,Attorney Represented,Attorney Represented Desc,Service Co. TPA Code/Carrier Code,Service Co. TPA Code/Carrier Code Name,DVC/Fireman's Fund Flag,DVC/Fireman's Fund Flag Desc,Disney Claim Total Incurred,Disney Claim Total Paid,Disney Claim Total Reserve
0,1.0,WDW,2016-10-01,FY16,12_Sep,1145.0,NaT,WDWG2016115392,WDWG2016115392,2015,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
1,1.0,WDW,2016-10-01,FY16,12_Sep,1500.0,NaT,WDWG2016115471,WDWG2016115471,52,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
2,1.0,WDW,2016-10-01,FY16,12_Sep,1550.0,NaT,WDWG2016115483,WDWG2016115483,2,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
3,1.0,WDW,2016-10-01,FY16,12_Sep,2040.0,NaT,WDWG2016115694,WDWG2016115694,3,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
4,1.0,WDW,2016-10-02,FY17,1_Oct,1306.0,NaT,WDWG2016115758,WDWG2016115758,3,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,1.0,WDW,2024-07-01,FY24,10_Jul,1500.0,NaT,WDWG2024239437,WDWG2024239437,37,...,"No, Not in Litigation",N,No,SELF,Self-administered,NaN,NaN,2500.0,0.0,2500.0
12686,1.0,WDW,2024-07-01,FY24,10_Jul,1815.0,NaT,WDWG2024755400,WDWG2024755400,23,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
12687,1.0,WDW,2024-07-01,FY24,10_Jul,NaN,NaT,WDWG2024755325,WDWG2024755325,NaN,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
12688,1.0,WDW,2024-07-01,FY24,10_Jul,NaN,NaT,WDWG2024755338,WDWG2024755338,7,...,NaN,NaN,NaN,SELF,Self-administered,NaN,NaN,NaN,NaN,NaN
12689,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,12129,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
merged_df.to_csv('J:/Data/RMSA Analysis/0 - Team Working Files/10 - Nick/DAKRocksFY24.csv', index=False)